// Auto-generated by: npm run db:types
// Do not edit manually. Run `npm run db:types` after schema changes.
//
// Placeholder until you run: supabase gen types typescript --local
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: 'buyer' | 'designer' | 'admin'
      invite_status: 'draft' | 'paid' | 'published' | 'archived'
      section_type:
        | 'opening' | 'story' | 'schedule' | 'venue' | 'rsvp'
        | 'gallery' | 'travel' | 'gifts' | 'countdown' | 'dress_code' | 'faq' | 'custom'
      media_kind: 'opening_video' | 'hero_video' | 'background_music' | 'gallery_image' | 'illustration'
      media_status: 'uploading' | 'processing' | 'ready' | 'failed'
      order_status: 'pending' | 'paid' | 'failed' | 'refunded' | 'expired'
      extra_pricing: 'per_invite' | 'per_unit'
      theme_status: 'active' | 'coming_soon' | 'retired'
      theme_category: 'wedding' | 'save_the_date' | 'birthday'
      plan_code: 'save_the_date' | 'experience' | 'premium'
    }
  }
}
